import mongoose, { Schema } from 'mongoose';

const TripItinerarySchema = new Schema({
  tripId: { type: Schema.Types.ObjectId, ref: 'Trip', required: true, unique: true },
  days: [{ type: Schema.Types.Mixed }],
  availableTransportModes: { type: Schema.Types.Mixed },
  isAutoGenerated: Boolean,
  source: { type: String, enum: ['manual', 'imported', 'ai_generated'] },
  progress: { type: Schema.Types.Mixed },
}, { timestamps: true });

export default mongoose.models.TripItinerary || mongoose.model('TripItinerary', TripItinerarySchema);